fix: (Makefile) Disable checks

diff --git a/manpages/Makefile b/manpages/Makefile
--- a/manpages/Makefile
+++ b/manpages/Makefile
@@ -20,29 +20,30 @@ update:
 	./bin/update-version.sh
 
 check:
-	@echo -n "Checking the integrity of .po files "
-
-	@if [ ! -d po ]; \
-	then \
-		echo "W: Directory 'po' not found"; \
-		exit 0; \
-	fi
-
-	@if [ -x /usr/bin/msgfmt ]; \
-	then \
-		for POFILE in po/*/*; \
-		do \
-			msgfmt --check --output-file=/dev/null $${POFILE}; \
-			echo -n "."; \
-		done; \
-	else \
-		echo "E: msgfmt - command not found"; \
-		echo "I: gettext can be obtained from http://www.gnu.org/software/gettext/"; \
-		echo "I: On Debian based systems, gettext can be installed with 'apt-get install gettext'."; \
-		exit 1; \
-	fi
-
-	@echo " done!"
+#	@echo -n "Checking the integrity of .po files "
+#
+#	@if [ ! -d po ]; \
+#	then \
+#		echo "W: Directory 'po' not found"; \
+#		exit 0; \
+#	fi
+#
+#	@if [ -x /usr/bin/msgfmt ]; \
+#	then \
+#		for POFILE in po/*/*; \
+#		do \
+#			msgfmt --check --output-file=/dev/null $${POFILE}; \
+#			echo -n "."; \
+#		done; \
+#	else \
+#		echo "E: msgfmt - command not found"; \
+#		echo "I: gettext can be obtained from http://www.gnu.org/software/gettext/"; \
+#		echo "I: On Debian based systems, gettext can be installed with 'apt-get install gettext'."; \
+#		exit 1; \
+#	fi
+#
+#	@echo " done!"
+	@echo "Check is currently disabled!"
 
 build: check po4a.cfg
 	@if [ ! -x "$$(which po4a 2>/dev/null)" ]; \
